#ifndef __interaction_H__
#define __interaction_H__

#include "phonoc_array.h"

void set_phonon_triplets(Darray *frequencies,
			 Carray *eigenvectors,
			 Iarray *degeneracies,
			 char *phonon_done,
			 const Iarray *triplets,
			 const int *grid_address,
			 const int *mesh,
			 const Darray *fc2,
			 const Darray *svecs_fc2,
			 const Iarray *multi_fc2,
			 const double *masses_fc2,
			 const int *p2s_fc2,
			 const int *s2p_fc2,
			 const double unit_conversion_factor,
			 const double *born,
			 const double *dielectric,
			 const double *reciprocal_lattice,
			 const double *q_direction,
			 const double nac_factor,
			 const char uplo);
void interaction_degeneracy_grid(double *interaction,
				const int *degeneracy,
				const int triplets_grid[][3],
				const int band_indices[],
				const int num_triplets,
				const int num_band0,
				const int num_band);
void get_interaction(Darray *fc3_normal_squared,
		     const Darray *frequencies,
		     const Carray *eigenvectors,
		     const Iarray *triplets,
		     const int *grid_address,
		     const int *mesh,
		     const Darray *fc3,
		     const int *atc,
             const char* g_skip,
		     const Darray *shortest_vectors,
		     const Iarray *multiplicity,
		     const double *masses,
		     const int *p2s_map,
		     const int *s2p_map,
		     const int *band_indices,
		     const int is_sym_q,
		     const double cutoff_frequency,
		     const double cutoff_hfrequency,
             const double cutoff_delta);
#endif
